### PR TITLE
Problem runner

### PR DESCRIPTION
**Pull request by leon-schi**
This adds my (Leon Schiller) own problem named 'runner' for the fun contest

### CODE REVIEW

**Comment by Veladus** [comment]
I added my solution. In the description, you state `n,m <= 5\cdot 10^5` but the test cases only go up to `5\cdot 10^4`. Please change this.

**Comment by Veladus** [comment]
Some small additional things:
* Please remove the files generated by latex
* Add a sentence to the end of the output statement the if there are multiple solutions, any will be accepted.
* You can use `in.readInt(min, max)` to check for bounds (i.e. min <= val <= max).

**Comment by PFischbeck** [comment]
In addition to the comments above: Please also mention that there could be self-loops and multi-edges (connecting the same nodes).

**Comment by chistopher** [comment]
@leon-schi would you please address the mentioned issues.

**Pull request merged**
